#!/usr/bin/env python3
"""Extract \\newcommand / \\DeclareMathOperator definitions from supplement.tex
and write a MathJax config snippet that defines them as math macros, so
make4ht-produced HTML pages render the macros correctly."""

import json
import re
import sys
from pathlib import Path

SRC = Path("/tmp/supp-html/supplement.tex")
OUT_JS = Path("/tmp/supp-html/mathjax-macros.js")

# \newcommand\foo{body}            -> ('foo', None, 'body')
# \newcommand\foo[N]{body}         -> ('foo', N,    'body')
# \newcommand{\foo}{body}          -> ('foo', None, 'body')
# \newcommand{\foo}[N]{body}       -> ('foo', N,    'body')
# \DeclareMathOperator\foo{body}   -> ('foo', None, '\\operatorname{body}')
# \DeclareMathOperator*\foo{body}  -> ('foo', None, '\\operatorname*{body}')

def find_balanced(src: str, start: int) -> int:
    """Given src[start] == '{', return index of matching '}' (exclusive end)."""
    assert src[start] == '{', f"expected {{ at {start}, got {src[start]!r}"
    depth = 0
    i = start
    while i < len(src):
        c = src[i]
        if c == '\\':
            i += 2
            continue
        if c == '{':
            depth += 1
        elif c == '}':
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    raise ValueError(f"unbalanced braces starting at {start}")

def parse_macros(text: str):
    """Return list of (name, nargs_or_None, body) tuples."""
    macros = []
    # Strip line comments first (% ... to end-of-line, but not \%)
    cleaned_lines = []
    for line in text.splitlines():
        # find first un-escaped %
        i = 0
        while i < len(line):
            if line[i] == '\\' and i + 1 < len(line):
                i += 2
                continue
            if line[i] == '%':
                break
            i += 1
        cleaned_lines.append(line[:i])
    text = "\n".join(cleaned_lines)

    i = 0
    while i < len(text):
        m = re.search(r'\\(newcommand|renewcommand|DeclareMathOperator)(\*?)', text[i:])
        if not m:
            break
        cmd = m.group(1)
        star = m.group(2)
        start = i + m.end()
        # Skip whitespace
        while start < len(text) and text[start] in ' \t':
            start += 1
        # Name: either \foo or {\foo}
        if text[start] == '{':
            end_brace = find_balanced(text, start)
            name_token = text[start+1:end_brace-1].strip()
            after_name = end_brace
        else:
            mname = re.match(r'\\([A-Za-z@]+)', text[start:])
            if not mname:
                i = start + 1
                continue
            name_token = '\\' + mname.group(1)
            after_name = start + mname.end()
        if not name_token.startswith('\\'):
            i = after_name
            continue
        name = name_token[1:]
        # Skip whitespace
        j = after_name
        while j < len(text) and text[j] in ' \t':
            j += 1
        # Optional [N]
        nargs = None
        if j < len(text) and text[j] == '[':
            close = text.find(']', j)
            try:
                nargs = int(text[j+1:close])
            except ValueError:
                i = after_name
                continue
            j = close + 1
        # Skip whitespace
        while j < len(text) and text[j] in ' \t\n':
            j += 1
        # Body: {body}
        if j >= len(text) or text[j] != '{':
            i = after_name
            continue
        end_body = find_balanced(text, j)
        body = text[j+1:end_body-1]
        if cmd == 'DeclareMathOperator':
            wrapped = body.strip()
            if star:
                body = '\\operatorname*{' + wrapped + '}'
            else:
                body = '\\operatorname{' + wrapped + '}'
            nargs = None
        macros.append((name, nargs, body))
        i = end_body
    return macros

def main():
    text = SRC.read_text()
    macros = parse_macros(text)

    # Deduplicate by name (last wins, as in LaTeX with \renewcommand)
    seen = {}
    for name, nargs, body in macros:
        seen[name] = (nargs, body)

    # MathJax syntax: name: "body" or name: ["body", nargs]
    entries = {}
    for name, (nargs, body) in seen.items():
        # Strip leading/trailing whitespace from body
        body = body.strip()
        if nargs is None:
            entries[name] = body
        else:
            entries[name] = [body, nargs]

    # Emit JS
    js_obj = json.dumps(entries, indent=2)
    out = (
        "// Auto-generated by build-mathjax-macros.py — do not edit.\n"
        "// Extracted from supplement.tex \\newcommand definitions so that\n"
        "// MathJax can render \\insrate, \\delrate, \\alphabet, \\revsub, etc.\n"
        "window.MathJax = {\n"
        '  tex: {\n'
        '    tags: "ams",\n'
        f'    macros: {js_obj}\n'
        "  }\n"
        "};\n"
    )
    OUT_JS.write_text(out)
    print(f"Wrote {len(entries)} macros to {OUT_JS}", file=sys.stderr)

if __name__ == "__main__":
    main()
