// Auto-generated by build-mathjax-macros.py — do not edit.
// Extracted from supplement.tex \newcommand definitions so that
// MathJax can render \insrate, \delrate, \alphabet, \revsub, etc.
window.MathJax = {
  tex: {
    tags: "ams",
    macros: {
  "expect": "\\mathbb{E}",
  "Var": "\\mathrm{Var}",
  "Cov": "\\mathrm{Cov}",
  "gamclass": "g",
  "ngamclass": "G",
  "ratemult": "\\rho",
  "xpath": "\\mathbb{X}",
  "emcount": "\\mathcal{C}",
  "agecorrection": "\\mathcal{G}",
  "seq": "\\mathcal{S}",
  "state": "x",
  "insrate": "\\lambda",
  "delrate": "\\mu",
  "immrate": "\\nu",
  "ext": "r",
  "notext": "\\rho",
  "notkappa": "\\varphi",
  "hmmproc": "{\\mbox{HMM}}",
  "nclasses": "C",
  "main": "0",
  "diag": "{\\mbox{diag}}",
  "geomdist": "{\\mbox{Geometric}}",
  "catdist": "{\\mbox{Categorical}}",
  "mixture": "{\\mbox{Mix}}",
  "berndist": "{\\mbox{Bernoulli}}",
  "fragproc": "{\\mbox{Frag}}",
  "subproc": "{\\mbox{Subst}}",
  "tkflinks": "{\\mbox{Links}}",
  "tkffrags": "{\\mbox{TKF92}}",
  "dom": "n",
  "ndom": "\\mathcal{N}",
  "srcdom": "l",
  "destdom": "m",
  "domdist": "v",
  "bifdom": "n",
  "samedom": "\\delta(\\srcdom=\\destdom)",
  "samefrag": "\\delta(\\srcfrag=\\destfrag)",
  "ltrans": "\\mathcal{A}",
  "ctrans": "\\mathcal{B}",
  "ltransinv": "\\mathcal{G}",
  "ctransinv": "\\mathcal{H}",
  "frag": "f",
  "nfrag": "\\mathcal{F}",
  "srcfrag": "f",
  "destfrag": "g",
  "fragdist": "w",
  "class": "c",
  "nclass": "\\mathcal{C}",
  "classdist": "u",
  "anctok": "a",
  "destok": "b",
  "ancordestok": "a",
  "gap": "\\bullet",
  "alphabet": "\\mathcal{A}",
  "eqm": "\\pi",
  "exch": "Q",
  "symsub": "S",
  "revsub": "R",
  "evoltime": "T",
  "tkftrans": "\\tau",
  "tkfwfst": "\\mathbb{T}",
  "exptrans": "\\upsilon",
  "transnest": "\\chi",
  "emptyseg": "z",
  "nonemptytrans": "\\mathcal{T}",
  "slicetrans": "\\mathcal{U}",
  "nullpathsum": "\\mathcal{Z}",
  "domexit": "p_\\mathrm{out}",
  "domenter": "p_\\mathrm{in}",
  "betagamma": "\\beta^\\ast",
  "fraglen": "K",
  "model": "M",
  "sumidx": "k",
  "sta": "{\\tt S}",
  "mat": "{\\tt M}",
  "ins": "{\\tt I}",
  "del": "{\\tt D}",
  "fin": "{\\tt E}",
  "mnull": "{\\tt A}",
  "inull": "{\\tt B}",
  "dnull": "{\\tt C}",
  "smide": "\\{\\sta,\\mat,\\ins,\\del,\\fin\\}",
  "nonemptystates": "\\Psi",
  "xstate": "{\\tt X}",
  "ystate": "{\\tt Y}",
  "zstate": "{\\tt Z}",
  "ustate": "{\\tt U}",
  "vstate": "{\\tt V}",
  "waitm": "{\\tt V}",
  "waitd": "{\\tt W}",
  "emit": "\\Omega",
  "silent": "\\mathcal{Z}",
  "effT": "\\hat{T}",
  "emprob": "e",
  "pathE": "\\mathcal{E}",
  "nullcl": "N^\\ast",
  "WCFG": "\\mathcal{G}",
  "NT": "\\mathcal{N}",
  "TM": "\\Sigma",
  "PR": "\\mathcal{P}",
  "WF": "w",
  "PTT": "\\mathcal{T}",
  "pttstate": "q",
  "pttstates": "\\mathcal{Q}",
  "inputgrammar": "\\WCFG_{\\mathrm{in}}",
  "outputgrammar": "\\WCFG_{\\mathrm{out}}",
  "parsetree": "\\mathbf{t}",
  "inputtree": "\\parsetree^{\\mathrm{in}}",
  "outputtree": "\\parsetree^{\\mathrm{out}}",
  "treeweight": "W",
  "treeyield": "\\mathrm{yield}",
  "phylo": "\\mathcal{T}_{\\mathrm{phy}}",
  "branchlen": "d",
  "ancestor": "x",
  "descendant": "y",
  "nodecount": "n",
  "inside": "\\alpha",
  "outside": "\\beta",
  "beamwidth": "W",
  "matdom": "\\mathtt{MatDom}",
  "insdom": "\\mathtt{InsDom}",
  "deldom": "\\mathtt{DelDom}",
  "matdomend": "\\mathtt{MatDomEnd}",
  "insdomend": "\\mathtt{InsDomEnd}",
  "deldomend": "\\mathtt{DelDomEnd}",
  "matdomtype": [
    "\\mathtt{MatDomType}[#1]",
    1
  ],
  "insdomtype": [
    "\\mathtt{InsDomType}[#1]",
    1
  ],
  "deldomtype": [
    "\\mathtt{DelDomType}[#1]",
    1
  ],
  "mkfrag": [
    "\\mathtt{MatFrag}[#1]",
    1
  ],
  "mkifrag": [
    "\\mathtt{InsFrag}[#1]",
    1
  ],
  "mkdfrag": [
    "\\mathtt{DelFrag}[#1]",
    1
  ],
  "ikfrag": [
    "\\mathtt{IFrag}[#1]",
    1
  ],
  "dkfrag": [
    "\\mathtt{DFrag}[#1]",
    1
  ],
  "mkfragtype": [
    "\\mathtt{MatFragType}[#1,#2]",
    2
  ],
  "mkifragtype": [
    "\\mathtt{InsFragType}[#1,#2]",
    2
  ],
  "mkdfragtype": [
    "\\mathtt{DelFragType}[#1,#2]",
    2
  ],
  "ikfragtype": [
    "\\mathtt{IFragType}[#1,#2]",
    2
  ],
  "dkfragtype": [
    "\\mathtt{DFragType}[#1,#2]",
    2
  ],
  "mkfragemit": [
    "\\mathtt{MatEmit}[#1,#2]",
    2
  ],
  "mkifragemit": [
    "\\mathtt{InsEmit}[#1,#2]",
    2
  ],
  "mkdfragemit": [
    "\\mathtt{DelEmit}[#1,#2]",
    2
  ],
  "ikfragemit": [
    "\\mathtt{IEmit}[#1,#2]",
    2
  ],
  "dkfragemit": [
    "\\mathtt{DEmit}[#1,#2]",
    2
  ],
  "mkfragend": [
    "\\mathtt{MatFragEnd}[#1,#2]",
    2
  ],
  "mkifragend": [
    "\\mathtt{InsFragEnd}[#1,#2]",
    2
  ],
  "mkdfragend": [
    "\\mathtt{DelFragEnd}[#1,#2]",
    2
  ],
  "ikfragend": [
    "\\mathtt{IFragEnd}[#1,#2]",
    2
  ],
  "dkfragend": [
    "\\mathtt{DFragEnd}[#1,#2]",
    2
  ],
  "matmat": "\\mathtt{MM}",
  "matins": "\\mathtt{MI}",
  "matdel": "\\mathtt{MD}",
  "insins": "\\mathtt{II}",
  "deldel": "\\mathtt{DD}",
  "INCLUDEDFROMTKF": "1",
  "MIXDOMPAPER": "1",
  "ind": "\\mathrm{ind}",
  "imm": "\\mathrm{imm}",
  "Eij": [
    "\\expect\\!\\left[#1 \\;\\middle|\\; X(0)=i,\\, X(T)=j\\right]",
    1
  ],
  "pluseq": "\\mathrel{+}=",
  "mixcount": "N",
  "Q": "\\bm{Q}",
  "Hh": "\\bm{H}",
  "indel": "\\ensuremath{(\\lambda,\\mu,r)}",
  "TKF": "\\textsc{TKF}",
  "TKFDP": "\\textsc{TKF--DP}",
  "MixDom": "\\textsc{MixDom}",
  "BDI": "\\textsc{BDI}",
  "theequation": "\\thesection.\\arabic{equation}",
  "demote": "\\let\\OrigSection\\section\n  \\let\\OrigSubsection\\subsection\n  \\let\\OrigSubsubsection\\subsubsection\n  \\let\\section\\subsection\n  \\let\\subsection\\subsubsection\n  \\let\\subsubsection\\paragraph",
  "restore": "\\let\\section\\OrigSection\n  \\let\\subsection\\OrigSubsection\n  \\let\\subsubsection\\OrigSubsubsection",
  "section": [
    "",
    1
  ]
}
  }
};
